package ir.viratech.pond_ms.api.review.base;

import ir.viratech.pond_ms.model.review.Review;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * A base DTO for class "Review".
 * Do not edit this file.
 * It is an automatically generated class.
 *
 */
public abstract class BaseReviewSaveDTO extends ir.viratech.commons.api.dto.AbstractFullDTO<Review> {
	
	
	
	
	
	
	////////////////////
	// DTO Properties //
	////////////////////
	
	// uid
	
	private String uid;
	
	/**
	 * Getter for property "uid".
	 *
	 * @return the value of property "uid"
	 */
	@JsonProperty
	public String getUid() {
		return this.uid;
	}
	
	
	// title
	
	private String title;
	
	/**
	 * Getter for property "title".
	 *
	 * @return the value of property "title"
	 */
	@JsonProperty
	public String getTitle() {
		return this.title;
	}
	
	/**
	 * Setter for property "title".
	 *
	 * @param title the new value for property "title"
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	
	// rate
	
	private int rate;
	
	/**
	 * Getter for property "rate".
	 *
	 * @return the value of property "rate"
	 */
	@JsonProperty
	public int getRate() {
		return this.rate;
	}
	
	/**
	 * Setter for property "rate".
	 *
	 * @param rate the new value for property "rate"
	 */
	public void setRate(int rate) {
		this.rate = rate;
	}
	
	
	// text
	
	private String text;
	
	/**
	 * Getter for property "text".
	 *
	 * @return the value of property "text"
	 */
	@JsonProperty
	public String getText() {
		return this.text;
	}
	
	/**
	 * Setter for property "text".
	 *
	 * @param text the new value for property "text"
	 */
	public void setText(String text) {
		this.text = text;
	}
	
	
	// visitedDate
	
	private String visitedDate;
	
	/**
	 * Getter for property "visitedDate".
	 *
	 * @return the value of property "visitedDate"
	 */
	@JsonProperty
	public String getVisitedDate() {
		return this.visitedDate;
	}
	
	
	// visitType
	
	private String visitType;
	
	/**
	 * Getter for property "visitType".
	 *
	 * @return the value of property "visitType"
	 */
	@JsonProperty
	public String getVisitType() {
		return this.visitType;
	}
	
	/**
	 * Setter for property "visitType".
	 *
	 * @param visitType the new value for property "visitType"
	 */
	public void setVisitType(String visitType) {
		this.visitType = visitType;
	}
	
	
	
	/////////////////////////
	// save/load functions //
	/////////////////////////
	
	/**
	 * Loads this DTO from an entity object of type "Review".
	 * 
	 * @param review the entity object from which this DTO is loaded. 
	 */
	@Override
	public void loadFrom(Review review) {
		this.uid = review.getExtuid();
		this.title = review.getTitle();
		this.rate = review.getRate();
		this.text = review.getText();
		this.visitedDate = review.getVisitedDateString();
		this.visitType = review.getTypeOfVisit();
	}
	
	/**
	 * Saves this DTO to an entity object of type "Review".
	 * 
	 * @param review the entity object to which this DTO is saved. 
	 * @throws BadDtoEntityModificationException If this DTO is not valid for saving. 
	 */
	@Override
	public void saveTo(Review review) throws ir.viratech.commons.api.entity_modifier.BadDtoEntityModificationException {
		//Disabled save for property: uid
		review.setTitle(this.title);
		review.setRate(this.rate);
		review.setText(this.text);
		//Disabled save for property: visitedDate
		review.setTypeOfVisit(this.visitType);
	}
	
	
	
	//////////////
	// toString //
	//////////////
	
	@Override
	protected Map<String, Object> toStringData() {
		Map<String, Object> data = super.toStringData();
		data.put("uid", this.uid);
		data.put("title", this.title);
		data.put("rate", this.rate);
		data.put("text", this.text);
		data.put("visitedDate", this.visitedDate);
		data.put("visitType", this.visitType);
		return data;
	}
	
}
