package ir.viratech.pond_ms.api.review.base;

import ir.viratech.pond_ms.model.review.Review;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * A base DTO for class "Review".
 * Do not edit this file.
 * It is an automatically generated class.
 *
 */
public abstract class BaseReviewViewDTO extends ir.viratech.commons.api.dto.AbstractFullDTO<Review> {
	
	
	
	
	
	
	////////////////////
	// DTO Properties //
	////////////////////
	
	// uid
	
	private String uid;
	
	/**
	 * Getter for property "uid".
	 *
	 * @return the value of property "uid"
	 */
	@JsonProperty
	public String getUid() {
		return this.uid;
	}
	
	
	// title
	
	private String title;
	
	/**
	 * Getter for property "title".
	 *
	 * @return the value of property "title"
	 */
	@JsonProperty
	public String getTitle() {
		return this.title;
	}
	
	
	// rate
	
	private int rate;
	
	/**
	 * Getter for property "rate".
	 *
	 * @return the value of property "rate"
	 */
	@JsonProperty
	public int getRate() {
		return this.rate;
	}
	
	
	// text
	
	private String text;
	
	/**
	 * Getter for property "text".
	 *
	 * @return the value of property "text"
	 */
	@JsonProperty
	public String getText() {
		return this.text;
	}
	
	
	// creationDate
	
	private String creationDate;
	
	/**
	 * Getter for property "creationDate".
	 *
	 * @return the value of property "creationDate"
	 */
	@JsonProperty
	public String getCreationDate() {
		return this.creationDate;
	}
	
	
	// visitedDate
	
	private String visitedDate;
	
	/**
	 * Getter for property "visitedDate".
	 *
	 * @return the value of property "visitedDate"
	 */
	@JsonProperty
	public String getVisitedDate() {
		return this.visitedDate;
	}
	
	
	// visitType
	
	private String visitType;
	
	/**
	 * Getter for property "visitType".
	 *
	 * @return the value of property "visitType"
	 */
	@JsonProperty
	public String getVisitType() {
		return this.visitType;
	}
	
	
	// voteUpCount
	
	private long voteUpCount;
	
	/**
	 * Getter for property "voteUpCount".
	 *
	 * @return the value of property "voteUpCount"
	 */
	@JsonProperty
	public long getVoteUpCount() {
		return this.voteUpCount;
	}
	
	
	// voteDownCount
	
	private long voteDownCount;
	
	/**
	 * Getter for property "voteDownCount".
	 *
	 * @return the value of property "voteDownCount"
	 */
	@JsonProperty
	public long getVoteDownCount() {
		return this.voteDownCount;
	}
	
	
	// user
	
	private ir.viratech.pond_ms.api.user.dto.UserReviewDTO user;
	
	/**
	 * Getter for property "user".
	 *
	 * @return the value of property "user"
	 */
	@JsonProperty
	public ir.viratech.pond_ms.api.user.dto.UserReviewDTO getUser() {
		return this.user;
	}
	
	/**
	 * Used for loading the property user from a given internal entity.
	 * 
	 * @param review the given internal entity
	 * @return the value of property user based on the given internal entity
	 */
	protected ir.viratech.pond_ms.api.user.dto.UserReviewDTO load_User(Review review) {
		ir.viratech.pond_ms.model.user.User __internalProperty_user = review.getUser();
		if (__internalProperty_user == null)
			return null; 
		ir.viratech.pond_ms.api.user.dto.UserReviewDTO user = new ir.viratech.pond_ms.api.user.dto.UserReviewDTO();
		user.loadFrom(__internalProperty_user);
		return user;
	}
	
	
	// replies
	
	private ir.viratech.commons.api.dto.PlainCollectionDTO<ir.viratech.pond_ms.model.review.ReplyReview, ir.viratech.pond_ms.api.review.dto.ReplyReviewViewDTO> replies;
	private boolean __modified__Replies = false;
	
	/**
	 * Getter for property "replies".
	 *
	 * @return the value of property "replies"
	 */
	@JsonProperty
	public ir.viratech.commons.api.dto.PlainCollectionDTO<ir.viratech.pond_ms.model.review.ReplyReview, ir.viratech.pond_ms.api.review.dto.ReplyReviewViewDTO> getReplies() {
		return this.replies;
	}
	
	/**
	 * Shows the modification state of the property "replies".
	 * 
	 * @return true if the property is modified
	 */
	public boolean hasModifiedReplies() {
		return this.__modified__Replies;
	}
	
	/**
	 * Used for loading the property replies from a given internal entity.
	 * 
	 * @param review the given internal entity
	 * @return the value of property replies based on the given internal entity
	 */
	protected abstract ir.viratech.commons.api.dto.PlainCollectionDTO<ir.viratech.pond_ms.model.review.ReplyReview, ir.viratech.pond_ms.api.review.dto.ReplyReviewViewDTO> load_Replies(Review review);
	
	
	
	/////////////////////////
	// save/load functions //
	/////////////////////////
	
	/**
	 * Loads this DTO from an entity object of type "Review".
	 * 
	 * @param review the entity object from which this DTO is loaded. 
	 */
	@Override
	public void loadFrom(Review review) {
		this.uid = review.getExtuid();
		this.title = review.getTitle();
		this.rate = review.getRate();
		this.text = review.getText();
		this.creationDate = review.getCreationDateString();
		this.visitedDate = review.getVisitedDateString();
		this.visitType = review.getTypeOfVisit();
		this.voteUpCount = review.getVoteUpCount();
		this.voteDownCount = review.getVoteDownCount();
		this.user = this.load_User(review);
		this.replies = this.load_Replies(review);
	}
	
	/**
	 * Saves this DTO to an entity object of type "Review".
	 * 
	 * @param review the entity object to which this DTO is saved. 
	 * @throws BadDtoEntityModificationException If this DTO is not valid for saving. 
	 */
	@Override
	public void saveTo(Review review) throws ir.viratech.commons.api.entity_modifier.BadDtoEntityModificationException {
		//Disabled save for property: uid
		//Disabled save for property: title
		//Disabled save for property: rate
		//Disabled save for property: text
		//Disabled save for property: creationDate
		//Disabled save for property: visitedDate
		//Disabled save for property: visitType
		//Disabled save for property: voteUpCount
		//Disabled save for property: voteDownCount
		//Disabled save for property: user
		//Disabled save for property: replies
	}
	
	
	
	//////////////
	// toString //
	//////////////
	
	@Override
	protected Map<String, Object> toStringData() {
		Map<String, Object> data = super.toStringData();
		data.put("uid", this.uid);
		data.put("title", this.title);
		data.put("rate", this.rate);
		data.put("text", this.text);
		data.put("creationDate", this.creationDate);
		data.put("visitedDate", this.visitedDate);
		data.put("visitType", this.visitType);
		data.put("voteUpCount", this.voteUpCount);
		data.put("voteDownCount", this.voteDownCount);
		data.put("user", this.user);
		data.put("replies", this.replies);
		return data;
	}
	
}
